# Generated by Django 3.0.7 on 2022-04-11 09:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220112_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='modules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), default=list, size=None),
        ),
    ]
