# Generated by Django 3.0.7 on 2022-04-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220411_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetailrecord',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
