# Generated by Django 4.1.2 on 2022-10-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220412_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='num',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='0', max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='number',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], default='0', max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='query1',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='query2',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='radius',
            field=models.CharField(choices=[('0', '0'), ('250', '250'), ('500', '500'), ('1000', '1000')], default='0', max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('Single Target', 'Single Target'), ('MSISDN Linked', 'MSISDN Linked'), ('CellID Linked', 'CellID Linked')], default='Single Target', max_length=32),
        ),
    ]
