# Generated by Django 4.1.2 on 2022-11-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_job_num_job_number_job_query1_job_query2_job_radius_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedDataRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=32, null=True)),
                ('number', models.BigIntegerField(default=-1, null=True)),
                ('linkingReason', models.CharField(default=None, max_length=256, null=True)),
                ('party1CDRs', models.ManyToManyField(related_name='party1CDRs', to='api.calldetailrecord')),
                ('party2CDRs', models.ManyToManyField(related_name='party2CDRs', to='api.calldetailrecord')),
            ],
        ),
    ]
