# Generated by Django 4.1.2 on 2022-11-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_linkeddatarecords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkedDataRecords',
            new_name='LinkedDataRecord',
        ),
    ]
