# Generated by Django 4.1.2 on 2022-11-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_linkeddatarecords_linkeddatarecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='linkedDataJobId',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='linkedDataStatus',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('FINISHED', 'FINISHED'), ('FAILED', 'FAILED')], default='PENDING', max_length=32),
        ),
    ]
